name: Java CI with Gradle

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build ShopMC
        run: ./gradlew build
      - name: Upload Bukkit plugin
        uses: actions/upload-artifact@v4
        with:
          name: ShopMC plugin built on ${{ matrix.java }} JDK
          path: "build/libs/*.jar"