name: Java CI with Gradle

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 17 ]
      fail-fast: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v3.0.0
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: Build ShopMC
        run: ./gradlew build
      - name: Upload ShopMC
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ShopMC Built On ${{ matrix.java }} JDK
          path: "Spigot/build/libs/Itemszop*.jar"
      - name: Upload ShopMC
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ShopMC Built On ${{ matrix.java }} JDK
          path: "BungeeCord/build/libs/Itemszop*.jar"
      - name: Upload ShopMC
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ShopMC Built On ${{ matrix.java }} JDK
          path: "Velocity/build/libs/Itemszop*.jar"
      - uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: dev-build-jdk-${{ matrix.java }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Spigot/build/libs/Itemszop*.jar"
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "BungeeCord/build/libs/Itemszop*.jar"
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}
      - name: Release the build
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Velocity/build/libs/Itemszop*.jar"
          body: ${{ join(github.event.commits.*.message, '\n') }}
          prerelease: true
          name: JDK ${{ matrix.java }} Dev-build
          tag: dev-build-jdk-${{ matrix.java }}